# Generated by Django 5.1.2 on 2024-10-28 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('expenseCategory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expenseCategory_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseName',
            fields=[
                ('expense_name_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('expenseType_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expenseType_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('incomeCategory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incomeCategory_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('incomeSource_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incomeSource_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('incomeType_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incomeType_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpend_app.expensecategory')),
                ('expense_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpend_app.expensename')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpend_app.expensetype')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('income_name', models.CharField(max_length=255)),
                ('income_amount_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_amount_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_date', models.DateField()),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpend_app.incomecategory')),
                ('income_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpend_app.incomesource')),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpend_app.incometype')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('household_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='household_photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='xpend_app.user')),
            ],
        ),
    ]
