# Generated by Django 5.1.2 on 2024-10-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='xpend_app.user'),
        ),
        migrations.AddField(
            model_name='household',
            name='users',
            field=models.ManyToManyField(null=True, related_name='households', to='xpend_app.user'),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='xpend_app.user'),
        ),
    ]
