# Generated by Django 5.1.2 on 2024-10-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpend_app', '0002_remove_household_user_expense_user_household_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_category',
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
    ]
